# Generated by Django 2.2.10 on 2020-02-27 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sprint8', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(default='pic_folder/None/no-img.jpg', upload_to='img/'),
        ),
    ]
