# Generated by Django 2.2.10 on 2020-03-02 14:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sprint8', '0005_auto_20200302_1238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cesta',
            name='clientes',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='cesta',
            name='productos',
        ),
        migrations.AddField(
            model_name='cesta',
            name='productos',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sprint8.Producto'),
        ),
        migrations.DeleteModel(
            name='Cliente',
        ),
    ]
