# Generated by Django 2.2.10 on 2020-03-03 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sprint8', '0006_auto_20200302_1550'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cesta',
            name='total',
        ),
    ]
