# Generated by Django 2.2.10 on 2020-03-04 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sprint8', '0007_remove_cesta_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cesta',
            name='productos',
        ),
        migrations.AddField(
            model_name='cesta',
            name='productos',
            field=models.ManyToManyField(to='sprint8.Producto'),
        ),
    ]
