# Generated by Django 2.2.10 on 2020-03-10 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sprint8', '0009_auto_20200304_1531'),
    ]

    operations = [
        migrations.AddField(
            model_name='cesta',
            name='estado',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='cesta',
            name='precio',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='stock',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='cesta',
            name='cantidad',
            field=models.IntegerField(null=True),
        ),
    ]
