# Generated by Django 2.2.10 on 2020-03-10 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sprint8', '0010_auto_20200310_1130'),
    ]

    operations = [
        migrations.AddField(
            model_name='cesta',
            name='total',
            field=models.FloatField(null=True),
        ),
    ]
