# Generated by Django 2.2.10 on 2020-03-10 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sprint8', '0011_cesta_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cesta',
            name='estado',
            field=models.BooleanField(default=True, verbose_name='Estado'),
        ),
    ]
