# Generated by Django 2.2.10 on 2020-03-10 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sprint8', '0012_auto_20200310_1235'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cesta',
            name='precio',
        ),
    ]
