# Generated by Django 2.2.10 on 2020-03-10 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sprint8', '0013_remove_cesta_precio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cesta',
            old_name='total',
            new_name='sub_total',
        ),
    ]
